###
GET http://localhost:5000/api/chat/chats
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsIm5hbWUiOiJBbGV4Iiwic3VybmFtZSI6IkRpbG9uIiwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInVzZXJuYW1lIjoidXNlckAyOTE2NDkiLCJhdmF0YXIiOiIvdXNlckAyOTE2NDkvYXZhdGFyLnBuZyIsImlhdCI6MTc0NzQ5MzYwMCwiZXhwIjoxNzQ3NDk1NDAwfQ.qQQFmHXe63uUkxA7dPSHNAxT2Sn94vUY0XP8KHyBY8o

Cookie: refresh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsIm5hbWUiOiJBbGV4Iiwic3VybmFtZSI6IkRpbG9uIiwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInVzZXJuYW1lIjoidXNlckAyOTE2NDkiLCJhdmF0YXIiOiIvdXNlckAyOTE2NDkvYXZhdGFyLnBuZyIsImlhdCI6MTc0NzQ5MzYwMCwiZXhwIjoxNzUwMDg1NjAwfQ.9Dx_6xXVyJWG-ifEMRtNnda7C2Tw9EYcOhZ0bpCGGeM

{
  "id": "27"
}
